openapi: 3.2.0
info:
  title: Authentication ACH Returns Deposit Method Configs API
  version: 1.0.0
  description: This resource is used for authentication actions
  contact:
    name: Rainforest
    email: support@rainforestpay.com
    url: https://rainforestpay.com
servers:
- url: https://api.sandbox.rainforestpay.com
  description: Sandbox server
- url: https://api.rainforestpay.com
  description: Production server
security:
- BearerAuth: []
tags:
- name: Deposit Method Configs
  description: Resources for deposit method config functions.
paths:
  /v1/deposit_method_configs:
    post:
      operationId: create_deposit_method_config
      summary: Create deposit method config
      description: Create the configuration to store a deposit method. The configuration contains basic information about the deposit method such as an idempotency key and optional information such as billing contact and metadata. If the billing contact is provided in the deposit method config, then the web component will not prompt for this data. These fields include name for an ACH deposit method. This allows a deposit method to be set up before collecting the sensitive deposit method details (i.e the account number) via the web component.
      parameters:
      - $ref: '#/paths/~1v1~1deposits/get/parameters/0'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/paths/~1v1~1deposit_method_configs/post/responses/200/content/application~1json/schema/properties/data'
              required:
              - platform_id
              - idempotency_key
            examples:
              required_fields:
                value:
                  idempotency_key: e7d57c41-7626-4644-b777-9451ab3ddea9
                  platform_id: plt_2WaOekua4ZUEgUFCxNBsASulZMa
              billing_contact:
                value:
                  idempotency_key: e7d57c41-7626-4644-b777-9451ab3ddea9
                  billing_contact:
                    name: Jane Smith
                    address_line_1: 3423 Piedmont Rd
                    address_line_2: Suite 123
                    city: Atlanta
                    state: GA
                    postal_code: '30305'
                    country: US
                    email: janesmith@example.com
                    phone: '4041234567'
              metadata:
                value:
                  idempotency_key: e7d57c41-7626-4644-b777-9451ab3ddea9
                  metadata:
                    key1: value1
                    key2:
                      inner_key1: inner_value1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                properties:
                  status:
                    $ref: '#/paths/~1v1~1deposits/get/responses/200/content/application~1json/schema/properties/status'
                  data:
                    type: object
                    properties:
                      deposit_method_config_id:
                        readOnly: true
                        description: "The unique deposit method config identifier. \n\nPrefix is \"dmc\" in production and \"sbx_dmc\" in sandbox."
                        type: string
                        example: dmc_2DrDPKzdQypRudLd8DhQKZX27dA
                      platform_id:
                        description: "The unique platform identifier. \n\nPrefix is \"plt\" in production and \"sbx_plt\" in sandbox."
                        type: string
                        example: plt_2DrDypu8n6IX7EVTjAnEd1dkTBa
                      idempotency_key:
                        description: A unique identifier provided by the platform. This key will be used to detect subsequent retries of the same request. Subsequent requests with the same key will return the result of the first request, regardless if the first request succeeded or failed. This identifier should be generated by the platform and can be max 255 characters.
                        type: string
                        example: e7d57c41-7626-4644-b777-9451ab3ddea9
                        maxLength: 255
                        minLength: 1
                      billing_contact:
                        $ref: '#/paths/~1v1~1deposit_methods/post/requestBody/content/application~1json/schema/properties/billing_contact'
                      allowed_sources:
                        description: The allowed deposit method sources for deposit method creation. If omitted, the allowed sources will default to all the allowed sources set on the platform configuration.
                        type: array
                        items:
                          type: string
                          enum:
                          - ENCRYPTED_ACH
                          - PARTNER_PLAID
                      metadata:
                        description: 'Valid JSON key-value object specified by the platform to store additional information on the payment method. Keys are queryable in list endpoints. Do not use the metadata field to store sensitive or confidential data.


                          Metadata must be less than 8 KB in size.

                          '
                        type: object
                        example:
                          key1: value1
                          key2:
                            inner_key1: inner_value1
                        minLength: 0
                      created_at:
                        description: Date and time deposit method config was created at in UTC RFC 3339 format.
                        type: string
                        format: date-time
                        example: '2022-01-01T12:00:00Z'
                        readOnly: true
                  errors:
                    $ref: '#/paths/~1v1~1deposits/get/responses/200/content/application~1json/schema/properties/errors'
        '400':
          $ref: '#/paths/~1v1~1deposits/get/responses/400'
        '401':
          $ref: '#/paths/~1v1~1deposits/get/responses/401'
        '403':
          $ref: '#/paths/~1v1~1deposits/get/responses/403'
        5XX:
          $ref: '#/paths/~1v1~1deposits/get/responses/5XX'
      tags:
      - Deposit Method Configs
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: APIKey
